const mapText = 
`################
..###########...
....#####.......
.....##.........
................
................
................
................
................
................
................
................
....###.........
..########......
.#############..
################`;

const chunk = loadChunk(mapText);

async function loadFile(path) {
    const response = await fetch(path);
    const text = await response.text();
    return text;
}
function loadChunk(text) {
    return text.split(/\r?\n/).join("");
}
